# Generated by Django 4.2.7 on 2023-12-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_name_taskcategory_categoryname_and_more'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=255)),
                ('taskDescription', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('taskAssignDate', models.DateField()),
                ('categories', models.ManyToManyField(blank=True, to='category.taskcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='TaskModel',
        ),
    ]
