# Generated by Django 4.2.7 on 2023-12-17 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Brand',
        ),
    ]
